import Head from "next/head";

export default function Home() {
   const themeSwitcher = () => {
      if (localStorage.getItem("theme") === "light") {
         localStorage.setItem("theme", "dark");
      } else {
         localStorage.setItem("theme", "light");
      }

      if (document.documentElement.classList.contains("dark") === true) {
         document.documentElement.classList.remove("dark");
      } else {
         document.documentElement.classList.add("dark");
      }
   };

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
         </Head>
         <div className="container mx-auto">
            <button
               onClick={themeSwitcher}
               className="m-5 border border-blue-400 px-5 py-2 rounded-md"
            >
               Change
            </button>

            <div className="bg-blue-300 dark:bg-slate-800 p-3 rounded-md text-center">
               Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores
               autem vero unde ipsam? Impedit et omnis iusto ad sapiente
               accusantium amet! Eius impedit a reprehenderit odit! Vel veniam
               at veritatis.
            </div>
         </div>
      </>
   );
}
